# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "azure" ]
  pull_request:
    branches: [ "azure" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'
        
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: java-app
    - name: Upload application
      uses: appleboy/scp-action@master
      with:       
        host: ${{ secrets.SERVER_IP_ADDRESS }}        
        username: ${{ secrets.SERVER_USERNAME }}      
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "*.jar"      
        target: "~/source"
    - name: Start Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}       
        username: ${{ secrets.SERVER_USERNAME }}     
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
            sudo systemctl stop BakeYourLife
            mv ~/source/BakeYourLife.jar ~/source/BakeYourLife-old.jar
            mv ~/source/BakeYourLife-0.0.1-SNAPSHOT.jar ~/source/BakeYourLife.jar
            sudo systemctl start BakeYourLife
            rm ~/source/BakeYourLife-old.jar
